### PR TITLE
Enable receiving non-SMIL messages

### PR DESCRIPTION
**Pull request by doflah**
Don't error out - just let the decode process continue.

### CODE REVIEW

**Comment by alfonsosanchezbeato** [comment]
@doflah, thanks for creating the PR. But before moving this forward, I would like to know more about the scenario when you get this kind of MMS without SMIL, to know if it a real use case. Could you provide more information on this?

**Comment by doflah** [comment]
While trying to get MMS to work, I used the e-mail gateway (number@tmomail.net with a picture attachment) and it didn't work until I removed those lines.  I'm not sure if the same thing happens with phone-to-phone MMS or if it is just the way T-Mobile handles e-mail.  I could try looking into it more thoroughly if you'd like.

**Comment by alfonsosanchezbeato** [comment]
Ok, got it. We can then test this easily, so no worries. Phone-to-phone is different, SMIL is used there by T-Mobile (and now it is working in devel-proposed + github master in case you want to give it a try).

**Comment by sergiusens** [comment]
Since this doesn't break backwards, it should be good.

**Pull request merged**
