### PR TITLE
Ensure that multiple recipients is supported

### PR DESCRIPTION
**Pull request by mandel-macaque**
Fix issue #14 by adding the TO field several times (one per recipient) and adapt the structures accordingly to have a []string in the To field instead of a string.

### CODE REVIEW

**Comment by mandel-macaque** [comment]
Looks like the failure is realted with getting the code.google.com/p/go.tools/cmd/cover in onde of the workers.. I don't think it should be a blocker.

**Comment by sergiusens** [comment]
Can you change .travis.yml?

$ go get code.google.com/p/go.tools/cmd/cover

the code.google.com/p/go.tools/cmd/cover command has moved; use golang.org/x/tools/cmd/cover instead.

**Comment by sergiusens** [comment]
next time use --amend! ;-)

**Comment by mandel-macaque** [comment]
Yes, I'm too used to bzr :-/

**Pull request merged**
