### PR TITLE
Fix decoder crash

### PR DESCRIPTION
**Pull request by alfonsosanchezbeato**
Fix

https://bugs.launchpad.net/ubuntu/+source/nuntium/+bug/1461107

and make decoding more robust.

### CODE REVIEW

**Comment by sergiusens** [comment]
This looks great, thanks for adding a decoding test as well.

Since you asked @mandel-macaque to review I'll wait for him to push the bullet. It's a +1 from my point of view.

**Comment by alfonsosanchezbeato** [comment]
@sergiusens, thanks for the review. I have pulled it again because I found an issue with the array limits checks.

**Comment by mandel-macaque** [comment]
A small comment from my side, in the diff I can see this pattern repeated several times:

field := reflectedPdu.FieldByName(hdr)
+		if field.IsValid() {
+			field.SetUint(uint64(v))
+			dec.log = dec.log + fmt.Sprintf("Setting %s to %#x == %d\n", hdr, v, v)
+		} else {
+			log.Println("Field", hdr, "not in decoding structure")
+		}

The only difference is that in some cases we are setting the field to be a uint64 and in other a string. Could we move the check of isValid and the logging to a diff function that does the checks and sets the value? That way do not need to copy paste the logic.

**Comment by alfonsosanchezbeato** [comment]
Refreshed addressing @mandel-macaque comment

**Comment by mandel-macaque** [comment]
I was considering the usage of a lmabda or a closure to achieve function composition. for example: func (dec *MMSDecoder) setPduField(pdu *reflect.Value, name, v interface, setter func(pdu.Field, interface) void) {

    if name != "" {
	field := pdu.FieldByName(name)
        if field.IsValid() {
	    setter(field, v)
	    dec.log = dec.log + fmt.Sprintf("Setting %s to %s\n", name, v)
	} else {
	    log.Println("Field", name, "not in decoding structure")
	}
    }
}

Usage:

setPduFiend(pdu, name, func(field pdu.Field, v interface){field.setString(v)}

**Comment by alfonsosanchezbeato** [comment]
Refreshed addressing @mandel-macaque comment

**Pull request merged**
